name: Next.js Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:  # Global environment variables for the entire workflow
  MONGODB_URI: 'mongodb://localhost:27017/CallerId-Status-Checker'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Specify your Node.js version

    - name: Install dependencies
      run: npm install --force

    - name: Run build
      run: npm run build

    - name: Run Start
      run: npm start
